[package]
name = "solenoid"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
hex = "0.4"
i256 = "0.2.2"
once_cell = "1.19"
primitive-types = "0.13.1"
thiserror = "1.0"
tiny-keccak = { version = "2.0.0", features = ["sha3"] }
