[package]
name = "solenoid"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
eyre = "0.6.12"
hex = "0.4"
i256 = "0.2.2"
once_cell = "1.19"
primitive-types = "0.13.1"
reqwest = { version = "0.12.22", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "1.0"
tiny-keccak = { version = "2.0.0", features = ["keccak"] }
tokio = { version = "1.46.1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
