[package]
name = "solenoid-t8n"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
eyre = "0.6.12"
rlp = "0.6.1"
hex = "0.4.3"
